excluded: Pods
disabled_rules:
  - control_statement
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - legacy_constructor
  - line_length
  - opening_brace
  - todo
  - trailing_semicolon
  - type_body_length
  - variable_name
